config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  
  resources :articles do 
    resources :comments
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end
 

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public','private','archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end
  
  def archived? 
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "blog", password: "blogpassword", except:  [:index, :show]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new 
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "blog", password: "blogpassword", only: :destroy
  
  def create 
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :status %><br>
    <%= f.select :status, ['public','private','archived'], selected: 'public' %>
  </div>
  
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_navigation.html.erb
<ul class="flex shadow">
  <li><%= link_to 'Edit', edit_article_path(@article) %></li>
  <li>|</li>
  <li><%= link_to 'Back', articles_path %></li>
</ul>

app/views/articles/edit.html.erb
<h1>Edit ARticle</h1>

<%= render "form", article: @article %>

<%= render 'navigation' %>

app/views/articles/index.html.erb
  <h1>Articles</h1>
  <br>
  <div>
    <% @articles.each do |article| %>
      <% unless article.archived? %>
        <div>
          <%= link_to article.title, article %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

<ul class="flex shadow">
  <li><%= link_to 'Back', articles_path %></li>
</ul>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= render 'navigation' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.select :status, ['public','private','archived'], selected: 'public' %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>